
SELECT ACTNO,BNAME FROM DEPOSIT
   where BNAME!='VRCE'
        AND  CNAME='MINU'
		AND ACTNO>102;
--Selected

SELECT TOP 5 * FROM BRANCH
  --WHERE --CITY='NAGPUR',
        --city NOT in ('NAGPUR','DELHI'),
        --S_ID BETWEEN 110 AND 125;

SELECT * FROM BORROW
   ORDER BY CNAME ASC
   --ORDER BY CNAME, BNAME
   ORDER BY CNAME DESC
--DISTINCT FOR UNIQUE
