/*update deposit 
set AMOUNT=5000
 where AMOUNT=3000;*/

 /*update BORROW
 set BNAME='C.G.ROAD'
 where CNAME='ANIL'*/

 /*UPDATE DEPOSIT
 SET ACTNO=111,AMOUNT=5000
 WHERE CNAME='SANDIP'*/

 /*UPDATE BORROW
 SET AMOUNT=AMOUNT+(AMOUNT*10/100)*/

 /*UPDATE DEPOSIT
 SET AMOUNT=5000
 WHERE ACTNO>=103 AND ACTNO<=107*/

 /*UPDATE BORROW
 SET AMOUNT=NULL
 WHERE LOANNO=321*/

--SELECT CNAME FROM BORROW WHERE AMOUNT IS NULL

