create procedure selectall
as
select s.rno,s.name,s.branch,r.spi
from student s
inner join result r
on s.rno=r.rno

CREATE PROCEDURE SELECTPK
@RNO INT
AS
SELECT S.RNO,S.NAME,S.BRANCH,R.SPI
FROM STUDENT S
INNER JOIN  RESULT R
ON S.RNO=R.RNO
WHERE S.RNO=@RNO

EXEC SELECTPK 102

CREATE PROCEDURE STUDENTINSERT
@RNO INT,
@NAME VARCHAR(50),
@BRANCH VARCHAR(50)
AS
INSERT INTO STUDENT
VALUES(@RNO,@NAME,@BRANCH)

CREATE PROCEDURE STUDENTUPDATE
@RNO INT,
@BRANCH VARCHAR(50)
AS
UPDATE STUDENT 
SET
BRANCH=@BRANCH
WHERE RNO=@RNO

EXEC STUDENTDELETE 107

SELECT * FROM Student

CREATE PROCEDURE STUDENTDELETE
@RNO INT
AS
DELETE FROM Student
WHERE RNO=@RNO

EXEC SP_HELP SELECTALL
EXEC SP_HELPTEXT SELECTALL
EXEC SP_DEPENDS SELECTALL